sudo: false
elixir:
  - 1.7
  - 1.8
  - 1.9
  - 1.10
otp_release:
  - 19.0
  - 20.0
  - 21.0
  - 22.0
  - 23.0
matrix:
  exclude:
    - elixir: 1.8
      otp_release: 19.0
    - elixir: 1.8
      otp_release: 23.0
    - elixir: 1.9
      otp_release: 19.0
    - elixir: 1.9
      otp_release: 23.0
    - elixir: 1.10
      otp_release: 19.0
    - elixir: 1.10
      otp_release: 20.0
cache:
  directories:
    - _build
    - deps
script:
  - mix test
  - if [[ `elixir -v` = *"1.8"* ]]; then mix format --check-formatted; fi
  - if [[ `elixir -v` = *"1.8"* ]]; then
      travis_wait 30 mix dialyzer --halt-exit-status --format term;
    fi
