language: elixir
elixir:
  - 1.8
  - 1.9
  - 1.10
otp_release:
  - 20.3
  - 21.3
  - 22.3
  - 23.0
matrix:
  exclude:
    - elixir: 1.8
      otp_release: 23.0
    - elixir: 1.9
      otp_release: 23.0
    - elixir: 1.10
      otp_release: 20.3
cache:
  directories:
    - _build
    - deps
script:
  - mix test
  - mix format --check-formatted
  - if [[ `elixir -v` = *"1.8"* ]]; then
      travis_wait 30 mix dialyzer --halt-exit-status --format term;
    fi
